DoctorsOffice/Models/Doctor.cs
using System.Collections.Generic;
using System;

namespace DoctorsOffice.Models
{
  public class Doctor
  {
    public int DoctorId { get; set; }
    public string Name { get; set; }
    public List<Patient> Patients { get; set; }
    public List<Specialty> Specialties { get; set; }
    public List<DoctorPatient> JoinEntities { get; }
    public List<DoctorSpecialty> JoinClasses { get; }
  }
}

DoctorsOffice/Models/DoctorPatient.cs
namespace DoctorsOffice.Models
{
  public class DoctorPatient
  {
    public int DoctorPatientId { get; set; }
    public int PatientId { get; set; }
    public Patient Patient { get; set; }
    public int DoctorId { get; set; }
    public Doctor Doctor { get; set; }

  }
}

DoctorsOffice/Models/DoctorSpecialty.cs
namespace DoctorsOffice.Models
{
  public class DoctorSpecialty
  {
    public int DoctorSpecialtyId { get; set; }
    public int DoctorId { get; set; }
    public Doctor Doctor { get; set; }
    public int SpecialtyId { get; set; }
    public Specialty Specialty { get; set; }

  }
}

DoctorsOffice/Models/DoctorsOfficeContext.cs
using Microsoft.EntityFrameworkCore;

namespace DoctorsOffice.Models
{
  public class DoctorsOfficeContext : DbContext
  {
    public DbSet<Patient> Patients { get; set; }
    public DbSet<Doctor> Doctors { get; set; }
    public DbSet<Specialty> Specialties { get; set; }
    public DbSet<DoctorSpecialty> DoctorSpecialties { get; set; }
    public DbSet<DoctorPatient> DoctorPatients { get; set; }
    public DoctorsOfficeContext(DbContextOptions options) : base (options) { }
  }
}

DoctorsOffice/Models/Patient.cs
using System.Collections.Generic;
using System;

namespace DoctorsOffice.Models
{
  public class Patient
  {
    public int PatientId { get; set; }
    public int DoctorId { get; set; }
    public string Name { get; set; }
    public DateTime Birthdate { get; set; }
    public Doctor Doctor { get; set; }
    public List<DoctorPatient> JoinEntities { get; }

  }
}

DoctorsOffice/Models/Specialty.cs
using System.Collections.Generic;
using System;

namespace DoctorsOffice.Models
{
  public class Specialty
  {
    public int SpecialtyId { get; set; }
    public string Title { get; set; }
    public List<DoctorSpecialty> JoinClasses { get; }

  }
}

DoctorsOffice/Controllers/DoctorsController.cs
using Microsoft.AspNetCore.Mvc;
using DoctorsOffice.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace DoctorsOffice.Controllers
{
  public class DoctorsController : Controller
  {
    private readonly DoctorsOfficeContext _db;
    public DoctorsController(DoctorsOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Doctor> model = _db.Doctors
      .Include(patient => patient.JoinEntities)
      .ThenInclude(doctor => doctor.Patient)
      .ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.SpecialtyId = new SelectList(_db.Specialties, "SpecialtyId", "Title");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Doctor doctor, int specialtyId)
    {
      if (doctor.Name == null || specialtyId == 0)
      {
        return RedirectToAction("Create");
      }
      else
      {
        _db.Doctors.Add(doctor);
        _db.SaveChanges();
        _db.DoctorSpecialties.Add(new DoctorSpecialty() { SpecialtyId = specialtyId, DoctorId = doctor.DoctorId });
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Doctor thisDoctor = _db.Doctors
      .Include(patient => patient.JoinEntities)
      .ThenInclude(doctor => doctor.Patient)
      .FirstOrDefault(doctor => doctor.DoctorId == id);
      Doctor thisDoctorsSpecialties = _db.Doctors
      .Include(specialty => specialty.JoinClasses)
      .ThenInclude(doctor => doctor.Specialty)
      .FirstOrDefault(doctor => doctor.DoctorId == id);
      return View(thisDoctor);
    }

  }
}

DoctorsOffice/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace DoctorsOffice.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

DoctorsOffice/Controllers/PatientsController.cs
using Microsoft.AspNetCore.Mvc;
using DoctorsOffice.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http.Features;

namespace DoctorsOffice.Controllers
{
  public class PatientsController : Controller
  {
    private readonly DoctorsOfficeContext _db;
    public PatientsController(DoctorsOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Patient> model = _db.Patients.Include(patient => patient.Doctor).ToList();
      ViewBag.PageTitle = "View all patients";
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create (Patient patient)
    {
      if (patient.DoctorId == 0 || patient.Name == null)
      {
        return RedirectToAction("Create");
      }
      else
      {
        _db.Patients.Add(patient);
        _db.SaveChanges();
        _db.DoctorPatients.Add(new DoctorPatient() { DoctorId = patient.DoctorId, PatientId = patient.PatientId });
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Patient thisPatient = _db.Patients
        .Include(patient => patient.JoinEntities)
        .ThenInclude(patient => patient.Doctor)
        .FirstOrDefault(patient => patient.PatientId == id);
      return View(thisPatient);
    }

    public ActionResult AddDoctor(int id)
    {
      Patient thisPatient = _db.Patients.FirstOrDefault(patients => patients.PatientId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(thisPatient);
    }

    [HttpPost]
    public ActionResult AddDoctor(Patient patient, int doctorId)
    {
      #nullable enable
      DoctorPatient? joinEntity = _db.DoctorPatients.FirstOrDefault(join => (join.DoctorPatientId == doctorId && join.PatientId == patient.PatientId));
      #nullable disable
      if (joinEntity == null && doctorId != 0)
      {
        _db.DoctorPatients.Add(new DoctorPatient() { DoctorId = doctorId, PatientId = patient.PatientId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = patient.PatientId });
    }
  }
}

DoctorsOffice/Controllers/SpecialtiesController.cs
using Microsoft.AspNetCore.Mvc;
using DoctorsOffice.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http.Features;
using System;

namespace DoctorsOffice.Controllers
{
  public class SpecialtiesController : Controller
  {
    private readonly DoctorsOfficeContext _db;
    public SpecialtiesController(DoctorsOfficeContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Specialty> model = _db.Specialties.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Specialty specialty)
    {
      if (specialty.Title == null)
      {
        return RedirectToAction("Create");
      }
      else
      {
        _db.Specialties.Add(specialty);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    public ActionResult Details(int id)
    {
      Specialty thisSpecialty = _db.Specialties
      .Include(specialty => specialty.JoinClasses)
      .ThenInclude(specialty => specialty.Doctor)
      .FirstOrDefault(specialty => specialty.SpecialtyId == id);
      return View(thisSpecialty);
    }

    public ActionResult AddDoctor(int id)
    {
      Specialty thisSpecialty = _db.Specialties.FirstOrDefault(specialties => specialties.SpecialtyId == id);
      ViewBag.DoctorId = new SelectList(_db.Doctors, "DoctorId", "Name");
      return View(thisSpecialty);
    }

    [HttpPost]
    public ActionResult AddDoctor(Specialty specialty, int doctorId)
    {
      #nullable enable
      DoctorSpecialty? joinClass = _db.DoctorSpecialties.FirstOrDefault(join => join.DoctorId == doctorId && join.SpecialtyId == specialty.SpecialtyId);
      #nullable disable
      if (joinClass == null && doctorId != 0)
      {
        _db.DoctorSpecialties.Add(new DoctorSpecialty() { DoctorId = doctorId, SpecialtyId = specialty.SpecialtyId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = specialty.SpecialtyId });
    }
  }
}

DoctorsOffice/Views/Doctors/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor
@using DoctorsOffice.Models

<p><strong>Note:</strong>You need to have at least one specialty before you can add a doctor.</p>
<p>Go to @Html.ActionLink("this page", "Create", "Specialties") to create a specialty.</p>

<h4>Add a new doctor</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.Label("Select specialty")
  @Html.DropDownList("SpecialtyId")
  <input type="submit" value="Add new doctor" class="btn btn-primary"/>
}
<br>
<p>@Html.ActionLink("Back to doctors list", "Index")</p>
<p>@Html.ActionLink("Back to specialties list", "Index", "Specialties")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

DoctorsOffice/Views/Doctors/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Doctor
@using DoctorsOffice.Models
@using System.Collections.Generic;

<h2>Doctor Details</h2>
<hr/>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <h3>This doctor does not have any patients.</h3>
}
else
{
  <h4>Patients that this doctor sees:</h4>
  <ul>
    @foreach (DoctorPatient join in Model.JoinEntities)
    {
      <li>@join.Patient.Name</li>
    }
  </ul>
}

@if (@Model.JoinClasses.Count == 0)
{
  <h3>This doctor does not have any specialties.</h3>
}
else
{
  <h4>Specialties this doctor has:</h4>
  <ul>
    @foreach (DoctorSpecialty join in Model.JoinClasses)
    {
      <li>@join.Specialty.Title</li>
    }
  </ul>
}
<p>@Html.ActionLink("Add new patient", "Create", "Patients")</p>
<p>@Html.ActionLink("Back to doctors list", "Index")</p>

DoctorsOffice/Views/Doctors/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models;

<h1>Doctors</h1>

@if (@Model.Count == 0)
{
  <h3>No doctors have been added yet!</h3>
}

<ul>
  @foreach (Doctor doctor in Model)
  {
    <li>@Html.ActionLink($"{doctor.Name}", "Details", new { id = doctor.DoctorId }) | This doctor is currently seeing @doctor.JoinEntities.Count patients.</li>
  }
</ul>

<p>@Html.ActionLink("Add new doctor", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

DoctorsOffice/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to your local doctor's office!</h1>
<p>@Html.ActionLink("See all patients", "Index", "Patients")</p>
<p>@Html.ActionLink("See all specialties", "Index", "Specialties")</p>
@* <p>@Html.ActionLink("See all doctors", "Index", "Doctors")</p> *@

DoctorsOffice/Views/Patients/AddDoctor.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient
@using DoctorsOffice.Models

<h2>Add a doctor</h2>

<h4>Add a doctor to this patient: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.PatientId)
  @Html.Label("Select doctor")
  @Html.DropDownList("DoctorId")
  <input type="submit" value="Save"/>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

DoctorsOffice/Views/Patients/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Patient

<p><strong>Note:</strong>You need to have at least one doctor before you can add a patient.</p>
<p>Go to @Html.ActionLink("this page", "Create", "Doctors") to create a doctor.</p>

<h4>Add a new patient</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <br>
  @Html.LabelFor(model => model.Birthdate)
  @Html.TextBoxFor(model => model.Birthdate, "{0:MM/dd/yyyy}", new { type = "date" })
  <br>
  @Html.LabelFor(model => model.Doctor)
  @Html.DropDownList("DoctorId")
  <br>
  <input type="submit" value="Add new patient" class="btn btn-primary"/>
}
<br>
<p>@Html.ActionLink("Back to patient list", "Index")</p>
<p>@Html.ActionLink("View doctors list", "Index", "Doctors")</p>

DoctorsOffice/Views/Patients/Details.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models
@model DoctorsOffice.Models.Patient

<h2>Patient Details</h2>
<hr/>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Birthdate): @Html.DisplayFor(model => model.Birthdate)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This patient does not see any doctors yet.</p>
}
else
{
  <h4>This patient sees the following doctors:</h4>
  <ul>
    @foreach(DoctorPatient join in Model.JoinEntities)
    {
      <li>@join.Doctor.Name</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add a doctor", "AddDoctor", new { id = Model.PatientId })</p>
<p>@Html.ActionLink("Back to patient list", "Index")</p>

DoctorsOffice/Views/Patients/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models;
@model List<DoctorsOffice.Models.Patient>;

<h1>Patients</h1>

@if (@Model.Count == 0)
{
  <h3>No patients have been added yet!</h3>
}
else
{
  <ul>
    @foreach (Patient patient in Model)
    {
      <li>@Html.ActionLink($"{patient.Name}", "Details", new { id = patient.PatientId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add new patient", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

DoctorsOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>@ViewBag.PageTitle</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>

DoctorsOffice/Views/Specialties/AddDoctor.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Specialty
@using DoctorsOffice.Models

<h2>Add a doctor</h2>

<h4>Add a doctor to this specialty: @Html.DisplayFor(model => model.Title)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.SpecialtyId)
  @Html.Label("Select doctor")
  @Html.DropDownList("DoctorId")
  <input type="submit" value="Add new doctor" class="btn btn-primary"/>
}
<br>
<p>@Html.ActionLink("View doctors list", "Index", "Doctors")</p>
<p>@Html.ActionLink("Back to specialties list", "Index", "Specialties")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>

DoctorsOffice/Views/Specialties/Create.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Specialty
@using DoctorsOffice.Models

<h4>Add a new specialty</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Title)
  @Html.TextBoxFor(model => model.Title)
  <br>
  <input type="submit" value="Add new specialty" class="btn btn-primary"/>
}
<br>
<p>@Html.ActionLink("Back to specialties list", "Index")</p>

DoctorsOffice/Views/Specialties/Details.cshtml
@{
  Layout = "_Layout";
}

@model DoctorsOffice.Models.Specialty
@using DoctorsOffice.Models
@using System.Collections.Generic;

<h2>Specialty Details</h2>
<hr/>
<h3>@Html.DisplayNameFor(model => model.Title): @Html.DisplayFor(model => model.Title)</h3>

@if (@Model.JoinClasses.Count == 0)
{
  <h3>This specialty does not have any doctors.</h3>
}
else
{
  <h4>Doctors who work in this specialty:</h4>
  <ul>
    @foreach (DoctorSpecialty join in Model.JoinClasses)
    {
      <li>@join.Doctor.Name</li>
    }
  </ul>
}
<p>@Html.ActionLink("Add an existing doctor", "AddDoctor", new { id = Model.SpecialtyId })</p>
<p>@Html.ActionLink("Create a new doctor", "Create", "Doctors")</p>
<p>@Html.ActionLink("View doctors list", "Index", "Doctors")</p>
<p>@Html.ActionLink("Back to specialties list", "Index")</p>

DoctorsOffice/Views/Specialties/Index.cshtml
@{
  Layout = "_Layout";
}

@using DoctorsOffice.Models;

<h1>Specialties</h1>

@if (@Model.Count == 0)
{
  <h3>No specialties have been added yet!</h3>
}

<ul>
  @foreach (Specialty specialty in Model)
  {
    <li>@Html.ActionLink($"{specialty.Title}", "Details", new { id = specialty.SpecialtyId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new specialty", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>